const stringTable = {
    "bullet.12ga.01_name": "12GA Flechette",
    "bullet.12ga.02_name": "12GA 7mm buckshot",
    "bullet.12ga.03_name": "12GA AP-20 Slug",
    "bullet.12ga.04_name": "12GA 12/70 RIP",
    "bullet.45acp.01_name": ".45acp AP",
    "bullet.45acp.02_name": ".45acp FMJ",
    "bullet.45acp.03_name": ".45acp L-Match",
    "bullet.545x39.01_name": "5.45x39mm 7N40",
    "bullet.545x39.02_name": "5.45x39mm BS",
    "bullet.545x39.03_name": "5.45x39mm FMJ",
    "bullet.545x39.04_name": "5.45x39mm PRS",
    "bullet.545x39.05_name": "5.45x39mm PP",
    "bullet.556x45.01_name": "5.56x45mm M995",
    "bullet.556x45.02_name": "5.56x45mm AP",
    "bullet.556x45.03_name": "5.56x45mm FMJ",
    "bullet.556x45.04_name": "5.56x45mm MK255",
    "bullet.556x45.05_name": "5.56x45mm MK318",
    "bullet.556x45.99_name": "5.56x45mm O.S.T.K.",
    "bullet.68x51.01_name": "6.8x51mm Hybird",
    "bullet.68x51.02_name": "6.8x51mm FMJ",
    "bullet.762x39.01_name": "7.62x39mm BP",
    "bullet.762x39.02_name": "7.62x39mm AP",
    "bullet.762x39.03_name": "7.62x39mm FMJ",
    "bullet.762x39.04_name": "7.62x39mm SP",
    "bullet.762x39.05_name": "7.62x39mm PS",
    "bullet.762x51.01_name": "7.62x51mm M61",
    "bullet.762x51.02_name": "7.62x51mm M993",
    "bullet.762x51.03_name": "7.62x51mm FMJ",
    "bullet.762x51.04_name": "7.62x51mm SP",
    "bullet.762x51.05_name": "7.62x51mm M80",
    "bullet.762x54r.01_name": "7.62x54R PS",
    "bullet.762x54r.02_name": "7.62x54R SNB",
    "bullet.762x54r.03_name": "7.62x54R FMJ",
    "bullet.762x54r.04_name": "7.62x54R HP",
    "bullet.762x54r.05_name": "7.62x54R LPS",
    "bullet.9x19.01_name": "9x19mm AP",
    "bullet.9x19.02_name": "9x19mm FMJ",
    "bullet.9x19.03_name": "9x19mm PSO",
    "bullet.9x19.04_name": "9x19mm Pst",
    "at.reflex-dot.walther-reflex_name": "Walther Reflex",
    "at.reflex-dot.cobra_name": "Cobra",
    "at.reflex-dot.pitechs3-bk_name": "PiTechS3 BK",
    "at.reflex-dot.toucan2_name": "Toucan2",
    "at.reflex-dot.ocp-7_name": "OCP-7",
    "at.reflex-dot.pitechs3-fde_name": "PiTechS3 FDE",
    "at.reflex-dot.t1-elevating_name": "T1 Elevating",
    "at.reflex-dot.savior_name": "Savior",
    "at.reflex-dot.fpo_name": "FPO",
    "at.reflex-dot.lomiot8t_name": "LOMIO8T",
    "at.scopes.acog_name": "ACOG",
    "at.scopes.hrma_name": "HRMA",
    "at.scopes.scepterdr-bk_name": "ScepterDR BK",
    "at.scopes.scepterdr-fde_name": "ScepterDR FDE",
    "at.scopes.beta4_name": "Beta4",
    "at.scopes.levo_name": "Levo",
    "at.com.rifle-compensator_name": "Rifle Compensator",
    "at.com.sniper-compensator_name": "Sniper Compensator",
    "at.com.smg-compensator_name": "SMG Compensator",
    "at.com.atk-1_name": "ATK-1",
    "at.com.atk-2_name": "ATK-2",
    "at.com.clr-bk_name": "CLR BK",
    "at.com.viper9_name": "Viper9",
    "at.com.predator_name": "Predator",
    "at.com.sugar-lump_name": "Sugar Lump",
    "at.com.clr-hiheat_name": "CLR HiHeat",
    "at.com.cooky_name": "COOKI",
    "at.powerscope.hunter3_name": "Hunter3",
    "at.powerscope.lpinighthawk_name": "LPNightHawk",
    "at.powerscope.vartac-x_name": "VerTac X",
    "at.rails.mp5-scoperail_name": "MP5 ScopeRail",
    "at.rails.pistol-tacticalrail_name": "Pistol TacticalRail",
    "at.rails.pkp-scoperail_name": "PKP ScopeRail",
    "at.rails.sks-scoperail_name": "SKS SopeRail",
    "at.rails.mlock-rail-bottom_name": "MLOK Rail Bottom",
    "at.rails.mlock-rail-side_name": "MLOK Rail Side",
    "at.rails.ar15-handle-rail_name": "AR15 Handle Rail",
    "at.rails.b18-74u_name": "B18 74U rail adpater",
    "at.rails.mtk-83-ak-side_name": "MTK-83 AK Side Rail adpater",
    "at.rails.rsr-ak-side_name": "RSR AK Side Rail adpater",
    "at.rails.45rail_name": "45 degree rail adpater",
    "at.laser.ac100-pistol-laser_name": "AC100 Pistol Laser",
    "at.laser.peq-laser_name": "PEQ Laser",
    "at.laser.faliro-laser_name": "Faliro Laser",
    "at.laser.faliro-laser-fde_name": "Faliro Laser FDE",
    "at.laser.mel-c1-laser_name": "MEL C1 Laser",
    "at.light.h200-flashlight_name": "H200 FlashLight",
    "at.light.mx400-flashlight_name": "MX400 FlashLight",
    "at.grip.tds-bk_name": "TDS BK",
    "at.grip.tds-olv_name": "TDS OLV",
    "at.grip.tds-sd_name": "TDS SD",
    "at.grip.afg_name": "AFG",
    "at.grip.mamba-bk_name": "Mamba BK",
    "at.grip.mamba-sd_name": "Mamba SD",
    "at.grip.mamba-olv_name": "Mamba OLV",
    "at.grip.transfer-bk_name": "Transfer BK",
    "at.grip.transfer-olv_name": "Transfer OLV",
    "at.grip.transfer-red_name": "Transfer Red",
    "at.grip.transfer-sd_name": "Transfer SD",
    "at.grip.stormgruff_name": "StormGruff",
    "at.grip.pvg-bk_name": "PVG BK",
    "at.grip.gf-mod.3-bk_name": "GF Mod.3 BK",
    "at.grip.gf-mod.3-fde_name": "GF Mod.3 FDE",
    "at.grip.gf-mod.3-olv_name": "GF Mod.3 OLV",
    "at.grip.pvg-olv_name": "PVG OLV",
    "at.grip.pvg-sd_name": "PVG SD",
    "at.grip.star5-bk_name": "STAR5 BK",
    "at.grip.star5-gy_name": "STAR5 GY",
    "at.grip.star5-olv_name": "STAR5 OLV",
    "at.grip.star5-sd_name": "STAR5 SD",
    "at.grip.tango-down_name": "Tango Down",
    "at.grip.pk-1_name": "PK-1",
    "at.grip.pk1b25u_name": "PK1B25U",
    "at.suppressor.rifle-suppressor_name": "Rifle Suppressor",
    "at.suppressor.pistol-suppressor_name": "Pistol Suppressor",
    "at.suppressor.arsd_name": "ARSD",
    "at.suppressor.sleipnir_name": "Sleipnir",
    "at.suppressor.quicker-bk_name": "Quicker BK",
    "at.suppressor.quicker-sd_name": "Quicker SD",
    "at.suppressor.mistrey46-gy_name": "Mistrey46 GY",
    "at.suppressor.sleipnir-bk-cover_name": "Sleipnir BK Cover",
    "at.suppressor.sleipnir-sd-cover_name": "Sleipnir SD Cover",
    "at.suppressor.mistrey46-sd_name": "Mistrey46 SD",
    "at.suppressor.pelican-9_name": "Pelican 9",
    "at.suppressor.sleipnir-mc-cover_name": "Sleipnir MC Cover",
    "at.suppressor.mp9_name": "MP9 Suppressor",
    "gun.ar15p_name": "AR15 Pistol 5.56x45 semi carbine rifle",
    "gun.m92_name": "M92 9x19mm pistol",
    "gun.mp5_name": "MP5 9x19mm SMG",
    "gun.bx4_name": "BX4 9x19mm SMG",
    "gun.evo3_name": "EVO3 9x19mm SMG",
    "gun.m1911_name": "M1911 .45ACP pistol",
    "gun.m1928_name": "M1928 .45ACP SMG",
    "gun.m3a1_name": "M3A1 .45ACP SMG",
    "gun.ump45_name": "UMP45 .45ACP SMG",
    "gun.m590_name": "M590 12Ga pump-shotgun",
    "gun.flame12_name": "Flame12 12Ga auto-shotgun",
    "gun.ak74_name": "AK74 Mod.T 5.45x39 assault rifle",
    "gun.ak74m_name": "AK74M 5.45x39  assault rifle",
    "gun.ak74n_name": "AK74N 5.45x39  assault rifle",
    "gun.ak74nmod1_name": "AK74N Mod.MMC 5.45x39 assault rifle",
    "gun.aks74u_name": "AKS74U 5.45x39 carbine rifle",
    "gun.malyuk545_name": "Malyuk545 5.45x39  carbine rifle",
    "gun.aks74uzt_name": "AKS74U Mod.FZ 5.45x39 carbine rifle",
    "gun.ar15h_name": "AR15 Hunter 5.56x45 semi assault rifle",
    "gun.m16a2_name": "M16A2 5.56x45 assault rifle",
    "gun.m4a1-agent_name": "M4A1‘Agent’ 5.56x45 carbine rifle",
    "gun.m4a1-cqbr_name": "M4A1‘CQBR’ 5.56x45 assault rifle",
    "gun.m4a1_name": "M4A1 5.56x45 assault rifle",
    "gun.m16a2gen2_name": "M16A2 GEN2 5.56x45 assault rifle",
    "gun.m4a1dd_name": "M4A1 Mod.DD 5.56x45 assault rifle",
    "gun.hk416_name": "RC416  5.56x45 assault rifle",
    "gun.seca16_name": "SECA16 5.56x45 assault rifle",
    "gun.m40a5_name": "M40A5 7.62x51 Bolt-action Sniper rifle",
    "gun.xm5_name": "XM5 6.8x51 assault rifle",
    "gun.mosin_name": "Mosin-1891 7.62x54R Bolt-action rifle",
    "gun.sks_name": "SKS 7.62x39  semi assault rifle",
    "gun.akmn_name": "AKMN 7.62x39 assault rifle",
    "gun.akmng_name": "AKMN-G 7.62x39 assault rifle",
    "gun.akmnglp_name": "AKMN-GLP 7.62x39 assault rifle",
    "gun.mxakm_name": "MX-AKM 7.62x39 assault rifle",
    "gun.akm_name": "AKM 7.62x39 assault rifle",
    "gun.pkp_name": "PKP 7.62x54R LMG",
    "gun.fal_name": "FAL 7.62x51 assault rifle",
    "gun.m1897_name": "M1897 12Ga pump-shotgun",
    "gun.sjogren_name": "‘Sjogren’ 12Ga auto-shotgun",
    "gun.ar308_name": "AR308 7.62x51 semi assault rifle",
    "gun.ar308lt_name": "AR308 LT 7.62x51 semi assault rifle",
    "gun.p250_name": "P250 9x19 pistol",
    "gun.mp9_name": "MP9 9x19mm SMG",
    "gun.mp9n_name": "MP9-N 9x19mm SMG",
    "gun.mp9t_name": "MP9-T 9x19mm SMG",
    "gun.malyuk762_name": "Malyuk762 7.62x39 carbine rifle",
    "gun.g18c_name": "G18C 9x19 automatic pistol",
    "gun.seca17bk_name": "SECA17 BK 7.62x51assault rifle",
    "gun.seca17fde_name": "SECA17 FDE 7.62x51assault rifle",
    "gun.seca17ssr_name": "SECA17 Mod.SSR 7.62x51assault rifle",
    "magazine.akm_name": "AKM 7.62x39  metal Mag 30-round",
    "magazine.aks74u_name": "AK74 5.45x39 Mag 30-round",
    "magazine.545y_name": "AK74 5.45x39 yellow Mag 30-round",
    "magazine.545p_name": "P-Mag 5.45x39 30-round",
    "magazine.bx4_name": "M92/BX4 9x19 Mag 25-Round",
    "magazine.evo3_name": "EVO3 9x19 Mag 30-round",
    "magazine.evo3.drum_name": "EVO3 9x19 Drum 50-round",
    "magazine.flame12_name": "Flame12 12Ga Mag 10-round",
    "magazine.hk416_name": "RC416 5.56x45 Mag 30-round",
    "magazine.m1911_name": "M1911 .45ACP  Mag 11-round",
    "magazine.m40a5.de_name": "M40A5 7.62x51 Mag 10-round",
    "magazine.m40a5.short_name": "M40A57.62x51 Mag 5-round",
    "magazine.m92_name": "M92/BX4 9x19 Mag 15-Round",
    "magazine.mp5_name": "Mp5 9x19 Mag 30-round",
    "magazine.pkp_name": "PKP 7.62x54R Drum 80-round",
    "magazine.xm5_name": "XM5 6.8x51 Mag 25-round",
    "magazine.m1928_name": "M1928 .45ACP Mag 25-round",
    "magazine.m3a1_name": "M3A1 .45ACP Mag 30-round",
    "magazine.sks_name": "SKS 7.62x39 Mag 15-Round",
    "magazine.fal_name": "FAL 7.62x51mm Mag 20-round",
    "magazine.seca16_name": "AR STANAG Mag 5.56x45 30-round",
    "magazine.ar15h_name": "AR STANAG Mag 5.56x45 20-round",
    "magazine.arp30_name": "P-Mag STANAG 5.56x45 30-round",
    "magazine.p60_name": "P-Drum STANAG 5.56x45 60-round",
    "magazine.sf60_name": "SF-Drum STANAG 5.56x45 60-round",
    "magazine.ard50_name": "AR-Drum STANAG 5.56x45 50-round",
    "magazine.ar30810_name": "AR308 7.62x51 Mag 10-round",
    "magazine.ar30820_name": "AR308 7.62x51 Mag 20-round",
    "magazine.p250_name": "P250 9x19 Mag13-round",
    "magazine.g18c17_name": "G18C 9x19 Mag 17-round",
    "magazine.g18c33_name": "G18C 9x19 Extend-Mag 17-round",
    "magazine.seca17bk_name": "SECA17 7.62x51mm Mag 20-round BK",
    "magazine.seca17fde_name": "SECA17 7.62x51mm Mag 20-round FDE",
    "magazine.762p30_name": "P-Mag 7.62x39 30-round",
    "magazine.545p60_name": "Pocco 5.45x39 Drum 60-round",
    "magazine.akmc10_name": "AKM 7.62x39  metal Mag 10-round",
    "magazine.akmp10b_name": "AKM 7.62x39  polymer Mag 10-round BK",
    "magazine.akmp10f_name": "AKM 7.62x39  polymer Mag 10-round FDE",
    "magazine.akmc20_name": "AKM 7.62x39  metal Mag 20-round",
    "magazine.akmp20d_name": "AKM 7.62x39  polymer Mag 20-round BK",
    "magazine.akmp20f_name": "AKM 7.62x39  polymer Mag 20-round FDE",
    "magazine.akmq60b_name": "AKM 7.62x39 Pro-Mag 60-round BK",
    "magazine.akmq60f_name": "AKM 7.62x39 Pro-Mag 60-round FDE",
    "magazine.akmd75_name": "AKM 7.62x39 Metal Drum 75-round",
    "magazine.mp9c15_name": "MP9 9x19 Mag 15-round",
    "magazine.mp9c20_name": "MP9 9x19 Mag 20-round",
    "magazine.mp9c30_name": "MP9 9x19 Mag 30-round",
    "magazine.ump45_name": "UMP45 .45ACP Mag 25-round",
    "grenade.01_name": "Flash",
    "grenade.03_name": "Smoke",
    "grenade.02_name": "M67 Hand grenade",
    "grenade.f1_name": "F-1 Hand grenade",
    "grenade.rgd5_name": "RGD-5 Hand grenade",
    "grenade.vog17_name": "VOG-17 Hand grenade",
    "grenade.vog25_name": "VOG-25 Hand grenade",
    "grenade.rgo_name": "RGO Hand grenade",
    "grenade.rgn_name": "RGN Hand grenade",
    "helmet.beanie_name": "Beanie hat",
    "helmet.gcap_name": "Green cap",
    "helmet.bkberet_name": "Beret Hat Black",
    "helmet.camoberet_name": "Beret Hat Camo",
    "helmet.0.7_name": "'SafetyFirst'",
    "helmet.1_name": "Bike protection helmet",
    "helmet.2_name": "Parachute Training helmet MC",
    "helmet.2bk_name": "Parachute Training helmet Black",
    "helmet.m1_name": "U.S. military M1 WWII helmet",
    "helmet.3_name": "6B47 Miltary helmet",
    "helmet.3.5_name": "PASGT helmet",
    "helmet.kiverf_name": "Kiver-M helmet",
    "helmet.4_name": "BlueLine SWAT headset helmet",
    "helmet.warrior_name": "Warrior Full Face helmet",
    "helmet.4.5_name": "OP Delta Force headset helmet",
    "helmet.achf_name": "ACH  helmet",
    "helmet.achfb_name": "ACH  helmet Black Camo",
    "helmet.5_name": "OP HighProtection helmet",
    "helmet.5.5n_name": "EVIRS helmet green camo",
    "helmet.5.5nk_name": "EVIRS headset helmet",
    "helmet.5.5_name": "EVIRS headset helmet green camo",
    "helmet.6_name": "RYS-T helmet",
    "helmet.bkberet.red_name": "Beret Hat Red",
    "helmet.skullfaceboss_name": "Skull Face Ops helmet",
    "hmat.mask.KiverM_name": "Kiver-M FaceShield",
    "hmat.mask.ACH_name": "ACH FaceShield",
    "hmat.mask.RYT_name": "RYS-T FaceShield",
    "hmat.nv.anpvs31_name": "AN/PVS 31 night vison",
    "vest.lv0_name": "NomadRig",
    "vest.lv1-sudden_name": "SuddenAttack",
    "vest.lv2_name": "SoftArmor",
    "vest.lv2-black_name": "RaidExplorer Black",
    "vest.lv2-sd_name": "RaidExplorer SD",
    "vest.lv3_name": "DuoMoutains",
    "vest.lv4_name": "JPC",
    "vest.lv5_name": "Rampage",
    "vest.lv5od_name": "Rampage OD",
    "vest.lv6_name": "ApexBK",
    "vest.lv7_name": "ApexMC",
    "vest.lv5-imtv_name": "IMTV",
    "vest.lv8_name": "WDCS",
    "vest.lv6iotv_name": "IOTV Gen3 HP Body Armor",
    "vest.fb012_name": "S.D. Protector Full Body Armor",
    "vest.fb012bk_name": "S.D. Protector Full Body Armor BK",
    "vest.skullboss_name": "Rampage Skull",
    "warfare.mica.device_name": "M.I.C.A. Device",
    "vestholster.02_name": "Grenade Pouch",
    "vestholster.03_name": "Mag Double Pouch",
    "vestholster.04_name": "Mag Pouch L",
    "vestholster.05_name": "Mag Pouch M",
    "vestholster.06_name": "Mag Pouch S",
    "vestholster.556F_name": "Standard Faster Mag holster",
    "vestholster.water_name": "Water Bottle Pouch",
    "backpack.rs_name": "Vagrant Rucksack",
    "backpack.lv1.01_name": "3DRT",
    "backpack.lv1.sportbag_name": "SportBag",
    "backpack.lv2.01_name": "EliteOps",
    "backpack.lv2.green_name": "EliteOps Green",
    "backpack.lv3.01_name": "6sh118",
    "backpack.bp007_name": "G.N.J.Backpack",
    "backpack.bp006_name": "HyperTec StorageBag",
    "medical.bandage_name": "Bandage",
    "medical.medical_needle_hp_lv1_name": "Civilian Syringe",
    "medical.medical_needle_hp_lv2_name": "Medical Syringe",
    "medical.medical_Pro_needle_lv1_name": "Military Syringe",
    "medical.medical_Pro_needle_lv2_name": "Advanced Syringe",
    "medical.brokenlimbrestorer_name": "Suturing Instrument",
    "medical.injector.kb-22_name": "KB-22 stimulant injector",
    "medical.injector.p4_name": "P4 stimulant injector",
    "medical.injector.adren_name": "Adrenaline injector",
    "medical.injector.hc_name": "H.C. stimulant injector",
    "medical.painkiller_name": "Painkiller",
    "medical.morphineneedle_name": "Morphine injector",
    "food.01_name": "Energy bar",
    "food.02_name": "Compact Ration",
    "food.03_name": "Soda",
    "food.04_name": "Water bottle",
    "food.05_name": "Apple",
    "food.06_name": "Beer",
    "food.07_name": "Coffee",
    "food.08_name": "Mineral water",
    "food.09_name": "Soda drink L",
    "food.10_name": "Chocolate",
    "food.11_name": "Meat can L",
    "food.12_name": "Meat can",
    "food.13_name": "Pea can",
    "food.14_name": "Sausage",
    "consumption.all.hqfuel.xl_name": "HQ Power Fuel Can L",
    "storage.all.ammobox.12ga_name": "12ga Ammo box",
    "storage.all.ammobox.45acp_name": "45acp Ammo box",
    "storage.all.ammobox.54539_name": "545x39 Ammo box",
    "storage.all.ammobox.55645_name": "556x45 Ammo box",
    "storage.all.ammobox.6851_name": "68x51 Ammo box",
    "storage.all.ammobox.76239_name": "762x39 Ammo box",
    "storage.all.ammobox.76251_name": "762x51 Ammo box",
    "storage.all.ammobox.76254r_name": "762x54r Ammo box",
    "storage.all.ammobox.919_name": "9x19 Ammo box",
    "storage.all.collectionbox_name": "Collection Box",
    "card.map1.beartown_h1_name": "Bearkery Storage Key",
    "card.map1.highbuilding_shop_name": "Office Building 2F Key",
    "card.map1.campshop_name": "Camp Shop’s Key",
    "card.map1.mall_chaneo_name": "Chaneo Store's Key",
    "card.map1.motel_201_name": "Motel Room 201 Key",
    "card.map1.motel_206_name": "Motel Room 206 Key",
    "card.map1.bear-police-f1_name": "Police Station 1F Key",
    "card.map1.bear-police-f2_name": "Police Station 2F Key",
    "card.map1.basementexit_name": "Suburb Western Bunker's Key",
    "card.map2.clifton_shop_name": "Ellie's Shop Key",
    "card.map2.dam_station_east_name": "East Dam Inlet's Key",
    "card.map2.dam_station_west_name": "West Dam Inlet's Key",
    "card.map2.dockhouse_name": "Dock Office's Key",
    "card.map2.factory_1_name": "Factory B zone Key",
    "card.map2.factory_2_name": "Factory A1 zone Key",
    "card.map2.midbunker_name": "Dam Central Bunker's Key",
    "card.map3.ExitLock_F3_sewer_name": "Lower Sewer exit’s Key",
    "card.map3.ExitLock_trainroad_name": "West railways exit's Key",
    "card.map3.armorHouse_name": "Armory's Key",
    "card.map3.FactoryRoom_name": "Sewer's room Key",
    "card.map3.officerRoom_name": "Officer's room Key",
    "card.map3.operatingRoom_name": "Medical lab's Key",
    "card.map3.DataStorage_name": "Data storage's Key",
    "consumption.all.hqfuel_name": "HQ Power Fuel Can",
    "valuable.information.notepad_name": "Notebook",
    "valuable.electric.remotecontrol_name": "Remote",
    "valuable.household.facialcleanser_name": "Cleanser",
    "valuable.household.cleaner_name": "Cleaner",
    "valuable.electric.mouse_name": "Mouse",
    "valuable.tools.screwdriver_name": "Screwdriver",
    "valuable.tools.wrench_name": "Wrench",
    "valuable.tools.hammer_name": "Hammer",
    "valuable.combustible.oilcan_name": "Oil can",
    "valuable.information.tape_name": "Tape",
    "valuable.information.videotape_name": "Videotape",
    "valuable.highvalue.csdollstandard_name": "CS Figure St",
    "valuable.information.floppydisk_name": "Floppydisk",
    "valuable.combustible.lighterfluid_name": "Lighter fluid",
    "valuable.building.copperwire_name": "Copper wire",
    "valuable.electric.wastechip_name": "wastechip",
    "valuable.combustible.gunpowder_name": "Gunpowder",
    "valuable.highvalue.badge_name": "Badge",
    "valuable.electric.radio_name": "Radio",
    "valuable.highvalue.silvercup_name": "Silver cup",
    "valuable.highvalue.goldcup_name": "Gold cup",
    "valuable.highvalue.camera_name": "Camera",
    "valuable.highvalue.pocketwatch_name": "Pocket watch",
    "valuable.electric.graphiccard_name": "Graphic card",
    "valuable.highvalue.csdollgold_name": "CS Figure G",
    "valuable.highvalue.goldingot_name": "Gold ingot",
    "valuable.highvalue.diamondring_name": "Diamond ring",
    "valuable.highvalue.fossil_name": "Fossil",
    "valuable.household.deodorant_name": "Deodorant",
    "valuable.combustible.gascan_name": "Gas can",
    "valuable.electric.cpu_name": "CPU",
    "valuable.electric.datacord_name": "Data Cord",
    "valuable.combustible.gunoil_name": "Gun oil",
    "valuable.building.insulatingtape_name": "Insulating Tape",
    "valuable.batteries.ionbattery_name": "Ion Battery",
    "valuable.building.nuts_name": "Nuts",
    "valuable.electric.cpufan_name": "CPU Fan",
    "valuable.household.pesticide_name": "Pesticide",
    "valuable.batteries.powerbank_name": "Power Bank",
    "valuable.building.bolts_name": "Bolts",
    "valuable.tools.sparkplug_name": "Spark Plug",
    "valuable.building.spraycan_name": "Spray can",
    "valuable.batteries.storagebattery_name": "Storage Battery",
    "valuable.building.superglue_name": "Super Glue",
    "valuable.tools.measuringtape_name": "Measuring Tape",
    "valuable.household.toiletpaper_name": "Toilet Paper",
    "valuable.combustible.wd40_name": "WD-40",
    "valuable.tools.wirecutter_name": "Wire Cutter",
    "valuable.tools.smallwrench_name": "Small Wrench",
    "valuable.electric.ram_name": "RAM",
    "valuable.electric.oldphone_name": "OldPhone",
    "valuable.electric.newphone_name": "NewPhone",
    "valuable.building.nail_name": "Nail",
    "valuable.building.piezometer_name": "Piezometer",
    "valuable.building.wire_name": "Wire",
    "valuable.building.valve_name": "Valve",
    "valuable.household.beardoil_name": "BeardOil",
    "valuable.household.soap_name": "Soap",
    "valuable.household.shampoo_name": "Shampoo",
    "valuable.household.toothpaste_name": "Toothpaste",
    "valuable.tools.electricdrill_name": "ElectricDrill",
    "valuable.tools.moldboard_name": "Moldboard",
    "valuable.tools.smallshovel_name": "SmallShovel",
    "valuable.tools.piler_name": "Plier",
    "valuable.combustible.largegascan_name": "Large gas can",
    "valuable.electric.civilradio_name": "Civil Radio",
    "valuable.electric.radioscanner_name": "Radio scanner",
    "valuable.batteries.sizedbattery1_name": "Size D battery1",
    "valuable.batteries.sizedbattery2_name": "Size D battery2",
    "valuable.tools.tapeholder_name": "Tape holder",
    "valuable.electric.flashlight_name": "Flash light",
    "valuable.electric.socket_name": "Socket",
    "valuable.building.bignut_name": "Big Nut",
    "valuable.tools.largeplier_name": "Large Plier",
    "valuable.household.rustcleaner_name": "Rust cleaner",
    "valuable.building.instantglue_name": "Instant glue",
    "valuable.tools.tiresealant_name": "Tire Sealant",
    "valuable.household.ratpoison_name": "Rat Poison",
    "valuable.building.ceramicadhesive_name": "Ceramic adhesive",
    "valuable.batteries.storagebattery2_name": "Small storage battery",
    "valuable.combustible.smokelesspowder_name": "Smokeless powder",
    "valuable.highvalue.antiqueteacup_name": "Antique Tea cup",
    "valuable.highvalue.stonelion_name": "Stone Lion",
    "valuable.highvalue.goldprize_name": "Gold Prize",
    "valuable.highvalue.goldelephant_name": "Golden Elephant",
    "valuable.highvalue.aladdinlamp_name": "Aladdin Lamp",
    "valuable.highvalue.csdollgold.2_name": "Medium Operator #2",
    "valuable.highvalue.csdollgold.3_name": "Elite Operator #3",
    "valuable.highvalue.csdollgold.4_name": "Heavy Operator #4",
    "valuable.highvalue.csdollgold.5_name": "Light Operator #5",
    "valuable.highvalue.csdollgold.6_name": "Operator #6",
    "valuable.highvalue.csdollgold.7_name": "Operator #7",
    "valuable.information.harddrive_name": "Hard Drive",
    "valuable.highvalue.contractors_name": "Contractors Game Disc",
    "valuable.highvalue.showdown_name": "ShowDown Game Disc",
    "valuable.highvalue.contractors_ed_name": "Contractors Game Disc Collector's Edition",
    "valuable.highvalue.showdown_ed_name": "ShowDown Game Disc Collector's Edition",
    "valuable.task.intelphone_name": "Ark Soldier's Phone",
    "valuable.task.tracker_name": "MS2000 Tracker",
    "valuable.task.maggie_camera_name": "Maggie's Camera",
    "valuable.task.maggie_medicalbag_name": "Maggie's Medical Bag",
    "valuable.task.maggie_radio_name": "Maggie's Radio",
    "valuable.task.johnny_drill_name": "Johnny's Drill",
    "valuable.task.johnny_familytape_name": "Johnny's FamilyTape",
    "valuable.task.policef1key_name": "Shooting Range Key",
    "valuable.task.igor_gunpowder_name": "Igor's GunPowder",
    "valuable.task.igor_sunglass_name": "Igor's Sunglass",
    "valuable.task.max_goldcup_name": "Maximilian's Golden Goblet",
    "valuable.task.max_goldIngot_name": "Maximilian's Golden Ingots",
    "valuable.task.tommy_baseball_name": "Tommy's Baseball Cam",
    "valuable.task.ark_floppydisk_name": "ARK Floppydisk",
    "valuable.task.ntg_medicalreport_name": "NTG Medical Report",
    "valuable.task.max_goldenearth_name": "Maximilian's Golden globe",
    "valuable.task.max_gamedisk_name": "Game Disk",
    "valuable.task.max_missile_name": "Missile Launcher",
    "valuable.task.max_plate1_name": "Antique Tea Plate - Yang",
    "valuable.task.max_plate2_name": "Antique Tea Plate - Yin",
    "exp.player_name": "Player EXP",
    "exp.weaponna_name": "ARK Arm Trust Point",
    "exp.weaponwp_name": "Regiment Trust Point",
    "exp.gear_name": "ARK Gear Trust Point",
    "exp.doctor_name": "NTG Trust Point",
    "exp.mall_name": "Trupiks Trust Point",
    "cash.wfdollar_name": "EZD",
    "exp.weaponna.unlock_name": "Unlock ARK Arms Dealer",
    "exp.weaponwp.unlock_name": "Unlock Regiment Arms Shop",
    "exp.gear.unlock_name": "Unlock ARK Protective Gear",
    "exp.doctor.unlock_name": "Unlock NTG Pharmacy",
    "exp.mall.unlock_name": "Unlock Trupiks Logistics",
    "backpack.robinson_name": "Robinson BFM Backpack",
    "backpack.odldos.flower_name": "Odldos flowers Backpack",
    "backpack.odldos.black_name": "Odldos black Backpack",
    "helmet.lh250_name": "LH-250 Pilot Helmet",
    "helmet.tsh4m_name": "Tsh-4M Tank Helmet",
    "vest.6b2_name": "6B2 body armor",
    "vest.press_name": "Press PACA body armor",
    "vest.security_name": "Security PACA body armor",
    "vest.police_name": "Police PACA body armor",
    "vest.6b17_": "6B17 body armor",
    "vest.6b17rig": "6B17 upgrade body armor",
    "magazine.g3_name": "G3SG1 7.62x51 Mag 20-round",
    "gun.g3sg1_name": "G3 7.62x51 assault rifle SG1",
    "vest.6b17_name": "6B17 body armor",
    "vest.6b17rig_name": "6B17 upgrade body armor",
    "card.map3.bomb_name": "Demolition Bomb",
    "valuable.highvalue.blindbox": "Blind Box",
    "event.xmas.bottle_name": "Holiday Bottle",
    "event.xmas.cookie_name": "Holiday Cookie",
    "vest.bells_name": "Rampage 'Bells'",
    "helmet.fast.xmas_name": "OP Fast 'Snowing'",
    "helmet.fast.xmasrd_name": "OP Fast 'Reindeer'",
    "helmet.hat.wbk_name": "White beard Killer",
    "helmet.fast.chrismas_name": "OP Fast 'Snowing'",
    "helmet.fast.chrismasrd_name": "OP Fast 'Reindeer'",
    "hmat.mask.LH250google_name": "LH250 Goggles",
    "hmat.mask.LH250mask_name": "LH250 Mask",
    "valuable.highvalue.blindbox_name": "Blind Box",
    "valuable.task.max_vr_name": "VR Headset",
    "gun.mosin.m38_name": "Mosin M38 7.62x54R Bolt-action carbine rifle",
    "gun.mosin.9130_name": "Mosin-91/30 7.62x54R Bolt-action sniper rifle",
    "gun.mosin.obrez_name": "Mosin \"Obrez\" 7.62x54R Bolt-action pistol",
    "gun.svt40_name": "SVT-40 7.62x54R semi-automatic rifle",
    "magazine.svt.10_name": "SVT-40 7.62x54R mag 10-round",
    "at.scopes.mosinpu_name": "Mosin PU 3.5X scope",
    "at.scopes.svtpu_name": "SVT PU 3.5X scope",
    "valuable.task.wyeth_wine_name": "Wyeth's Dry Red Wine",
    "card.map1.wyethfarm_name": "Wyeth Farm's Key",
    "at.ironsight.caffs_name": "CA Ironsight FFS black",
    "at.ironsight.caffs.fde_name": "CA Ironsight FFS FDE",
    "at.ironsight.caffs.olv_name": "CA Ironsight FFS Olive",
    "at.ironsight.cafrs_name": "CA Ironsight FRS black",
    "at.ironsight.cafrs.fde_name": "CA Ironsight FRS FDE",
    "at.ironsight.cafrs.olv_name": "CA Ironsight FRS Olive",
    "at.com.adaptor.aug556_name": "AUG 5.56x45 muzzle adapter",
    "magazine.aug9.25_name": "AUG 9x19 MP88 mag 25-round",
    "magazine.aug.30_name": "AUG 5.56x45 mag 30-round",
    "magazine.aug.42_name": "AUG 5.56x45 mag 42-round",
    "gun.aug.9para_name": "AUG A3 9x19 Para SMG Olive",
    "gun.aug.a1stg77_name": "AUG A1 STG77 5.56x45 assault rifle Olive",
    "gun.aug.a3stg77_name": "AUG A3 STG77 5.56x45 assault rifle FDE",
    "gun.aug.a3cqb_name": "AUG A3 CQB 5.56x45 assault rifle FDE",
    "gun.aug.a3ris_name": "AUG A3 RIS 5.56x45 assault rifle Black",
    "valuable.task.task_phone_name": "FotoVision+ Phone",
    "valuable.task.tommy_camera_name": "Tommy's cam",
    "valuable.task.maggie_toxin_name": "Maggie's poison",
    "valuable.task.maggie_medical_name": "X-NAX medicine",
    "valuable.task.igor_can_name": "Igor's can",
    "valuable.task.igor_box_name": "Igor's supplycase",
    "valuable.task.ark_telescope_name": "ARK Telescope",
    "valuable.task.maggie_herbs_name": "Maggie's herb",
    "valuable.task.maggie_line_name": "Signal enhancer",
    "valuable.task.igor_trash_name": "Igor's notes",
    "valuable.task.igor_memobeer_name": "Memorial beer",
    "valuable.task.max_phone_name": "Max's phone",
    "valuable.task.max_money_name": "Max's money",
    "valuable.task.max_diamondring_name": "Max's diamond ring",
    "valuable.task.johnny_minibox_name": "Johnny's Safebox",
    "valuable.task.johnny_talkie_name": "Johnny's walkie-talkie",
    "valuable.task.Igor_sharkdvd_a_name": "'SHARK'",
    "valuable.task.Igor_subwaydvd_a_name": "'Subway Scream'",
    "valuable.task.Igor_sharkdvd_b_name": "'SHARK' Sequel",
    "valuable.task.Igor_subwaydvd_b_name": "'Subway Scream 2'",
    "valuable.task.maggie_usb_name": "Maggie's USB",
    "valuable.household.SaltCan_name": "Salt can",
    "valuable.electric.LightBulb_name": "Energy-saving lamp",
    "valuable.MedicalSupplies.UVlight_name": "UV lamp",
    "valuable.electric.VisionModule_name": "Imaging module",
    "valuable.electric.DigitalSensor_name": "Digital sensor",
    "valuable.electric.TapePlayer_name": "Tape player",
    "valuable.electric.GameConsole_name": "Game console",
    "valuable.electric.Transformer_name": "Voltage transformer",
    "valuable.information.OpticalDisc_name": "CD",
    "valuable.information.HorrorNovel_name": "Horror novel",
    "valuable.information.Magazine_name": "Magazine",
    "valuable.information.Recorder_name": "Recorder",
    "valuable.information.ComputerTextbook_name": "Computer manual",
    "valuable.information.AntiqueBook_name": "Antiquarian Book",
    "valuable.batteries.MarineStorageBattery_name": "Marine battery",
    "valuable.combustible.match_name": "Matches",
    "valuable.combustible.OliveOil_name": "Olive oil",
    "valuable.tools.GasPipeWrench_name": "Gas pipe pliers",
    "valuable.tools.ClimbingRope_name": "Climbing rope",
    "valuable.MedicalSupplies.BandAid_name": "Band-aids",
    "valuable.MedicalSupplies.MedicalScissors_name": "Medical scissors",
    "valuable.MedicalSupplies.DisinfectingWipes_name": "Disinfectant wipes",
    "valuable.MedicalSupplies.AsthmaMedication_name": "Asthma medicine",
    "valuable.MedicalSupplies.Iodophor_name": "Iodine",
    "valuable.MedicalSupplies.Aspirin_name": "Aspirin",
    "valuable.MedicalSupplies.BottledGlucose_name": "Bottled glucose",
    "valuable.MedicalSupplies.MedicalKit_name": "Portable medical kit",
    "valuable.MedicalSupplies.Centrifuge_name": "Centrifuge",
    "valuable.MedicalSupplies.defibrillator_name": "Defibrillator",
    "valuable.highvalue.cash_name": "Stack of cash",
    "valuable.highvalue.GameCartridgeA_name": "'Showdown' Cart",
    "valuable.highvalue.GameCartridgeB_name": "'Contractors' Cart",
    "valuable.highvalue.GameCartridgeC_name": "'GrimLord' Cart",
    "valuable.highvalue.GameCartridgeD_name": "'Exfilzone' Cart",
    "valuable.highvalue.Perfume_name": "Perfume",
    "valuable.highvalue.GoldenKnife_name": "Golden short knife",
    "valuable.highvalue.CrimsonQueenRing_name": "Ruby ring",
    "valuable.highvalue.GoldenLionRing_name": "Gold lion ring",
    "valuable.highvalue.BullStatue_name": "Bull statue",
    "valuable.highvalue.MilitaryUSBdrive_name": "USB - classified ",
    "valuable.highvalue.MilitaryHardDrive_name": "Hard drive - classified ",
    "card.map4.Apartment_name": "Apartment 2F Key",
    "card.map4.BankF2_name": "Bank 2F Key",
    "card.map4.BankSewer_name": "Bank Sewer Key",
    "card.map4.HospitalF2_name": "Hospital 2F Key",
    "card.map4.ResortHotel_name": "Resort hotel 208 Key",
    "card.map4.Tunnel_name": "Sunset tunnel Key",
    "card.map4.Voyages_name": "Halif Voyage 1F storage room Key",
    "storage.all.magazinebox_name": "Mag&Attachment Box",
    "storage.all.medicalbox_name": "Medical Box",
    "storage.all.keybox_name": "Key Box",
    "sc.caselv0_name": "Pluto container",
    "sc.caselv1_name": "Mercury container",
    "sc.caselv1pro_name": "Mars container",
    "sc.caselv2_name": "Venus container",
    "sc.caselv2pro_name": "Callisto container",
    "sc.caselv3_name": "Titan container",
    "sc.caselv3pro_name": "Ganymede container",
    "sc.caselv4_name": "Uranus container",
    "sc.caselv4pro_name": "Neptune container",
    "at.scopes.falcon_name": "Falcon Scope 1.5-6X for G3 series",
    "at.scopes.psg_name": "Taco Scope 6-42X for PSG-1",
    "at.rails.bt3_name": "G3 scope rail PD3",
    "at.rails.hl_name": "G3 scope rail high lever",
    "at.rails.fab_name": "G3 scope rail PAD",
    "at.rails.psgrail_name": "PSG-1 scope rail",
    "gun.g3.hk91_name": "G3 7.62x51 assault rifle HK91",
    "gun.g3.ak4_name": "G3 7.62x51 assault rifle AK4",
    "gun.g3.spuhr_name": "G3 7.62x51 assault rifle SUPHR",
    "gun.g3.prs_name": "G3 7.62x51 assault rifle PRS",
    "gun.g3.hk51_name": "G3 7.62x51 assault rifle HK51",
    "gun.g3.hk51k_name": "G3 7.62x51 assault rifle HK51-K",
    "gun.g3.hk51ace_name": "G3 7.62x51 assault rifle HK51 ACE",
    "gun.g3.psg1_name": "PSG-1 7.62x51 Designated marksman rifle",
    "gun.g3a3_name": "G3 7.62x51 assault rifle A3",
    "magazine.g3.20_name": "G3series 7.62x51 Mag 20-round",
    "magazine.g3.10_name": "G3series 7.62x51 Mag 10-round",
    "magazine.g3.30_name": "G3series 7.62x51 Mag 30-round",
    "magazine.g3.50_name": "G3series 7.62x51 X-Drum 50-round black",
    "magazine.g3.50green_name": "G3series 7.62x51 X-Drum 50-round olive",
    "medical.bandage_lv1_name": "Gauze",
    "medical.bandage_lv2_name": "Bandage",
    "medical.bandage_lv3_name": "Military Bandage",
    "medical.brokenlimbrestorer_lv1_name": "Suturing Instrument R1",
    "medical.brokenlimbrestorer_lv2_name": "Suturing Instrument R2",
    "medical.brokenlimbrestorer_lv3_name": "Apex Suturing Instrument",
    "medical.painkiller_Lv1_name": "Painkiller L1",
    "medical.painkiller_Lv2_name": "Painkiller L2",
    "medical.painkiller_Lv3_name": "Military Painkiller",
    "valuable.highvalue.cashA_name": "A bundle of cash",
    "valuable.highvalue.cashB_name": "2 bundles of cash",
    "valuable.highvalue.cashC_name": "4 bundles of cash",
    "valuable.batteries.carbattery_name": "Vehicle battery",
    "vest.lv5-imtv.bonecrusher_name": "IMTV'Bonecrusher'",
    "hmat.mask.RYT.bonecrusher_name": "RYS-T FaceShield 'Bonecrusher'",
    "helmet.rys.bonecrusher_name": "RYS_T 'Bonecrusher'",
    "valuable.combustible.lighter.fix_name": "Lighter",
    "vest.lv8.swat_name": "WDCS 'SWAT'",
    "helmet.4.5.le_name": "OP Fast 'Law Enforcement'",
    "ticket.metro.entry_name": "Metro Entry Ticket",
    "storage.all.mini.collectionbox_name": "Collection Box Small"
}

module.exports = { stringTable };